### ISSUE TITLE
Pop up an error when invoking (POST) application method with "123" payload for a Express.js application

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-dapr#140] opened 2021-02-19 08:53 UTC
**OS:** Mac
**Build Version:** 0.4.0 

**Repro Steps:**

1. Create and initialize a new Express.js application -> Open the application folder in VS Code -> Create a launch.json file with "Node.js".
2. F1 -> Select "Dapr: Scaffold Dapr Tasks" -> Select "Launch Program" -> Open the "routes/users.js" file -> Add the following before the export statement:
   ```
      router.post('/', function (req, res, next) {
         res.send(req.body);
      });
   ```
3. F5 with the "Launch Program with Dapr". 
4. Right click the running application -> Select "Invoke (POST) Application Method" -> Enter "users" -> Enter a payload with **`123`**.
5. Check whether the method is invoked successfully.

**Expect:**
The method is invoked successfully.

**Actual:**
Pop up an error.![Screen Shot 2021-02-19 at 3 36 11 PM](https://user-images.githubusercontent.com/62053665/108473364-e66f1f80-72c8-11eb-891a-3b1616fb17d6.png)

**More Info:**

1. This issue doesn't reproduce for .NET Web API application.
2. This issue doesn't reproduce when publishing message with "123" payload.

**Comment by philliphoff** [comment] 2021-02-19 18:37
@v-mengwe Thanks for the submission!  I get the same error both when using `123` as well as `"123"` with a Express.js application.  The issue is that the JSON body parser of Express.js, by default, requires that the body be either a JSON object or array.  Hence, `{ "number": 42 }` as in the test case succeeds but `123` does not because the former is an object and the latter is a simple JSON number.

It's possible to configure the Express.js JSON body parser to accept *any* valid JSON value, but the Express.js application generator just doesn't do that out of the box, and I didn't see it as necessary for test purposes.  It is entirely possible that the ASP.NET Core body parser *does* support any valid JSON by default, hence the difference seen between the two platforms.

Since this doesn't appear to be an issue with the extension itself, I'm going to close this issue.  I'll make a note in the test docs about using JSON objects or arrays in the Express.js test case.

**Closed by philliphoff** 2021-02-19 18:37 UTC
Labels: AT-CTI
