### ISSUE TITLE
The result is inconsistent between executing "Invoke (POST) Application Method" and "Publish Message to Application" with a JSON payload "{number:42}" 

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-dapr#154] opened 2021-04-16 10:29 UTC
**OS:** Win10
**Build Version:** 20210409.1

**Repro Steps:**

1. Create and initialize a new Express.js application -> Open the application folder in VS Code -> Create a launch.json file with "Node.js".
2. F1 -> Select "Dapr: Scaffold Dapr Tasks" -> Select "Launch Program" -> Open the "routes/users.js" file -> Add the following before the export statement:

>      router.post('/', function (req, res, next) {
>       res.send(req.body);
>      });

3. F5 with the "Launch Program with Dapr".
4. Right click the running application -> Select "Invoke (POST) Application Method" -> Enter "users" -> Enter a payload with `"{mumber:42}"` -> Check the result.
5. Stop debug -> Open the "app.js" file and add the following after the "app.use('/users', …)" statement:	
```
  app.get('/dapr/subscribe', function(req, res, next) {
     res.json([{ 'pubsubname': 'pubsub', 'topic': 'topicA', 'route': 'topicA' }]);
  });
		
  app.post('/topicA', express.json({type: 'application/cloudevents+json'}), function(req, res, next){
     res.sendStatus(200);
  });
```	
6. F5 with the "Launch Program with Dapr".
7. Right click the running application -> Select "Publish Message to Application" -> Enter "pubsub" -> Enter "topicA" -> Enter a payload with `"{mumber:42}"` -> Check the result.
8. Check whether the result is consistent between the step 4 and step 7.

**Expect:**
The result is consistent between the step 4 and step 7.

**Actual:**
The result is inconsistent between the step 4 and step 7.
1. Invoke (POST) Application Method: fail.
    ![image](https://user-images.githubusercontent.com/62053665/115011417-2de8e500-9ee1-11eb-8601-b8851677fdfd.png)
3. Publish Message to Application: success.
    ![image](https://user-images.githubusercontent.com/62053665/115011559-5b359300-9ee1-11eb-9ca8-2a91329b9ba8.png)

**Comment by philliphoff** [comment] 2021-04-20 20:32
@v-mengwe I see what's happening.  In your case you've entered a JSON string `"{ number: 42 }"` that looks like a JavaScript object, but is not an actual JSON object.  However, `POST` requests *require* a JSON object (e.g. `{ "number": 42 }`) whereas event publications do not (and are fine with strings).

I would consider this "by design".  Let me know if I'm misunderstanding.

**Comment by v-mengwe** [comment] 2021-04-21 05:58
The prompt message is consistent when asking to enter a payload between the "Invoke (POST) Application Method" and "Publish Message to Application".
**Invoke (POST) Application Method:**
![image](https://user-images.githubusercontent.com/62053665/115503712-74f02500-a2a9-11eb-9143-c98f74018f93.png)
**Publish Message to Application:** 
![image](https://user-images.githubusercontent.com/62053665/115503762-89342200-a2a9-11eb-88a0-ca44d41cd98d.png)

**Comment by philliphoff** [comment] 2021-04-21 16:48
That is a good point, @v-mengwe.  While both allow a JSON payload, `POST` requests allow only a *subset* of all valid JSON (objects and arrays).  We *could* provide more specific instructions as well as more specific validation in that case.  I've added #155 to track that enhancement and will close this issue as "by design" (for now).

**Closed by philliphoff** 2021-04-21 16:48 UTC
Labels: AT-CTI, need-more-info
