### ISSUE TITLE
There is a duplicate "daprd-down" task in the TERMINAL after clicking "Restart" button for a stopped application

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-dapr#221] opened 2022-01-10 11:54 UTC
**OS:** All
**Build Version:** 20220108.1
**Regression:** Not a Regression

**Repro Steps:**

1. Create a new .NET 6.0 ASP.NET Web API application by "dotnet new webapi --no-https --name netwebapp".
2. Open the application in VS Code -> Select "Dapr: Scaffold Dapr Tasks" from Command Palette -> Select ".NET Core Launch (web)" when asked to select a configuration -> Enter an application ID (Select the default "app") -> Enter an application port (Select the default "5000").
3. Debug with configuration ".NET Core Launch (web) with Dapr".
4. Navigate to "Dapr" view -> Right click the "app" -> Select "Stop Application".
5. Click the "Restart" button to restart debugging.
6. Check whether there is no duplicate "daprd-down" task in the TERMINAL.

**Expect:**
There is no duplicate "daprd-down" task in the TERMINAL.

**Actual:**
There is a duplicate "daprd-down" task in the TERMINAL.
![dapr](https://user-images.githubusercontent.com/62053665/148758809-1a402a49-8b7a-4627-8465-c8194d2da036.gif)

**Comment by philliphoff** [comment] 2022-01-10 19:16
The `daprd-down` task is tied to the debug session's launch task; VS Code is responsible for launching it when debugging ends (or is restarted).  We'll need to investigate why is seems to be done twice.

**Comment by tillig** [comment] 2022-01-20 16:58
I get both `daprd-debug` _and_ `daprd-down` duplicates for every start/stop or restart iteration. It'd be nice if those were reused.

<img width="333" alt="Screen Shot 2022-01-20 at 8 56 34 AM" src="https://user-images.githubusercontent.com/1156571/150385506-09c211aa-3187-4ea0-bf67-630bd1763929.png">

**Comment by v-xinda** [comment] 2023-04-07 08:51
Verified this issue on the latest build 20230324.2, it doesn't reproduce. So close it.

**Closed by v-xinda** 2023-04-07 08:51 UTC
Labels: AT-CTI, investigate
